
ALTER SESSION SET CONTAINER=TEXTILABPDB;

CREATE USER app IDENTIFIED BY app123
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON USERS;

GRANT CONNECT, RESOURCE TO app;

GRANT CREATE SESSION TO app;
GRANT CREATE TABLE TO app;
GRANT CREATE SEQUENCE TO app;
GRANT CREATE VIEW TO app;
GRANT CREATE PROCEDURE TO app;
